# Generated by Django 5.0.6 on 2024-11-08 13:37

import APP.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=APP.models.generate_filename_with_timestamp)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=APP.models.generate_filename_with_timestamp)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BrandProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=APP.models.generate_filename_with_timestamp)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to=APP.models.generate_filename_with_timestamp)),
                ('brand_product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.brandproductcategory')),
            ],
        ),
        migrations.AddField(
            model_name='brandproductcategory',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.productcategory'),
        ),
    ]
